package com.hc360.drools;
import com.hc360.drools.bean.BusinChance;

/*
    类目算分
    是否有类目(0 有 1 没有)  有-- 100分     无-- 0分
*/
rule "category"
 when
    $b : BusinChance(hasSupCat == 0)
 then
    $b.setScore($b.getScore() + 100);
    $b.setHasSupCatScore(100);
 end


/*
    参数(基础参数)算分
    1<= 参数个数 <=5 -- 10分
    参数格式 > 5
        参数重复率
            0.6<= 重复率 < 0.7         repetitorAmount = 1     20分
            0.5<= 重复率 < 0.6         repetitorAmount = 2     40分
            0.4<= 重复率 < 0.5         repetitorAmount = 3     60分
            0.3<= 重复率 < 0.4         repetitorAmount = 4     80分
            重复率 < 0.3               repetitorAmount = 5     100分
*/

rule "paramI"
when
    $b : BusinChance(paramAmount >= 1 , paramAmount <= 5)
then
    $b.setScore($b.getScore() + 10);
    $b.setHasnoParam(10);
end

rule "paramII"
when
    $b : BusinChance(paramAmount >5 , repetitorAmount == 1)
then
    $b.setScore($b.getScore() + 20);
    $b.setHasnoParam(20);
end

rule "paramIII"
when
    $b : BusinChance(paramAmount >5 , repetitorAmount == 2)
then
    $b.setScore($b.getScore() + 40);
    $b.setHasnoParam(40);
end

rule "paramIV"
when
    $b : BusinChance(paramAmount >5 , repetitorAmount == 3)
then
    $b.setScore($b.getScore() + 60);
    $b.setHasnoParam(60);
end

rule "paramV"
when
    $b : BusinChance(paramAmount >5 , repetitorAmount == 4)
then
    $b.setScore($b.getScore() + 80);
    $b.setHasnoParam(80);
end

rule "paramF"
when
    $b : BusinChance(paramAmount >5 , repetitorAmount == 5)
then
    $b.setScore($b.getScore() + 100);
    $b.setHasnoParam(100);
end

/*
    标题算分
    标题中是否包含关键词(0 不包含 1 包含)   包含--100分 不包含--50分
*/
rule "titleI"
when
    $b : BusinChance(hasOtherTitleDetail == 1);
then
    $b.setScore($b.getScore() + 100);
    $b.setHaslongtitle(100);
end

rule "titleII"
when
    $b : BusinChance(hasOtherTitleDetail == 0);
then
    $b.setScore($b.getScore() + 50);
    $b.setHaslongtitle(50);
end


/*
    报价算分
    ① 是否支持在线交易
    ② 报价方式
        0 电话报价
        1 直接报价(区间、规格)
    ③ 价格条数

    ④ 报价方式得分判断条件

    ①为空或为0(不支持)
        ②为0
            ④设置为1           -- 20分
        ②不为0
                ④设置为2       --40分
            ③大于2
                ④设置为3       --80分

    ①为1
                ④设置为4       --80分
           ③大于2
                ④设置为5       --100分
*/

rule "offerPrice"
when
    $b : BusinChance(priceTypeNew == 1);
then
    $b.setScore($b.getScore() + 20);
    $b.setHasPrice(20);
end

rule "offerPriceI"
when
    $b : BusinChance(priceTypeNew == 2);
then
    $b.setScore($b.getScore() + 40);
    $b.setHasPrice(40);
end

rule "offerPriceII"
when
    $b : BusinChance(priceTypeNew == 3);
then
    $b.setScore($b.getScore() + 80);
    $b.setHasPrice(80);
end

rule "offerPriceIII"
when
    $b : BusinChance(priceTypeNew == 4);
then
    $b.setScore($b.getScore() + 80);
    $b.setHasPrice(80);
end

rule "offerPriceIV"
when
    $b : BusinChance(priceTypeNew == 5);
then
    $b.setScore($b.getScore() + 100);
    $b.setHasPrice(100);
end


/*
    图片算分
        图片数量
            1 --   20分
            2 --   30分
            >=3 -- 40分
        第一张图片大小(0-否 1-是)
            大于300 * 300 -- 60分
*/
rule "image"
when
    $b : BusinChance(imageAmount == 1)
then
    $b.setScore($b.getScore() + 20);
    $b.setPhotoCount(20);
end

rule "imageI"
when
    $b : BusinChance(imageAmount == 2)
then
    $b.setScore($b.getScore() + 30);
    $b.setPhotoCount(30);
end

rule "imageII"
when
    $b : BusinChance(imageAmount >= 3)
then
    $b.setScore($b.getScore() + 40);
    $b.setPhotoCount(40);
end

rule "imageIII"
when
    $b : BusinChance(firstInmageSize == 1)
then
    $b.setScore($b.getScore() + 60);
    $b.setFirstPhoto(60);
end

/*
    详细内容算分
        内容字数
                字数 < 150        1    -- 10分
                150 <=字数 <=300  2    -- 20分
                字数 >= 300       3    -- 50分
        图片宽度分布算分
                700像素以上
                    一张      -- 40分
                    两张      -- 50分
                    两张以上   -- 80分
                500至700像素
                       一张      -- 30分
                       两张      -- 50分
                       两张以上   -- 70分
                300至500像素
                       一张      -- 20分
                       两张      -- 40分
                       两张以上   -- 60分
                300以下
                       一张      -- 10分
                       两张      -- 30分
                       两张以上   -- 50分
*/
rule "detailWordNumI"
when
    $b : BusinChance(detailWordAmountType == 1);
then
    $b.setScore($b.getScore() + 10);
    $b.setDetailWordScore(10);
end

rule "detailWordNumII"
when
    $b : BusinChance(detailWordAmountType == 2);
then
    $b.setScore($b.getScore() + 20);
    $b.setDetailWordScore(20);
end

rule "detailWordNumIII"
when
    $b : BusinChance(detailWordAmountType == 3);
then
    $b.setScore($b.getScore() + 50);
    $b.setDetailWordScore(50);
end

/*
    宽度大于 700
*/
rule "detailImageThanSevenI"
when
    $b : BusinChance(thanSevenHundred == 1);
then
    $b.setScore($b.getScore() + 40);
    $b.setDetailImages(40);
end

rule "detailImageThanSevenII"
when
    $b : BusinChance(thanSevenHundred == 2);
then
    $b.setScore($b.getScore() + 50);
    $b.setDetailImages(50);
end

rule "detailImageThanSevenIII"
when
    $b : BusinChance(thanSevenHundred >= 2);
then
    $b.setScore($b.getScore() + 80);
    $b.setDetailImages(80);
end

/*
    宽度 500 至 700
*/
rule "detailImageFiveBetweenSevenI"
when
    $b : BusinChance(fiveBetweenSeven == 1)
then
    $b.setScore($b.getScore() + 30);
    $b.setDetailImages($b.getDetailImages() + 30);
end

rule "detailImageFiveBetweenSevenII"
when
    $b : BusinChance(fiveBetweenSeven == 2)
then
    $b.setScore($b.getScore() + 50);
    $b.setDetailImages($b.getDetailImages() + 50);
end

rule "detailImageFiveBetweenSevenIII"
when
    $b : BusinChance(fiveBetweenSeven >= 2)
then
    $b.setScore($b.getScore() + 70);
    $b.setDetailImages($b.getDetailImages() + 70);
end

/*
    宽度  300 至 500
*/
rule "detailImageThreeBetweenFiveI"
when
    $b : BusinChance(threeBetweenFive == 1);
then
    $b.setScore($b.getScore() + 20);
    $b.setDetailImages($b.getDetailImages() + 20);
end

rule "detailImageThreeBetweenFiveII"
when
    $b : BusinChance(threeBetweenFive == 2);
then
    $b.setScore($b.getScore() + 40);
    $b.setDetailImages($b.getDetailImages() + 40);
end

rule "detailImageThreeBetweenFiveIII"
when
    $b : BusinChance(threeBetweenFive >= 2);
then
    $b.setScore($b.getScore() + 60);
    $b.setDetailImages($b.getDetailImages() + 60);
end

/*
    宽度 300以下
*/
rule "detailImageLessThreeI"
when
    $b : BusinChance(lessThreeHundred == 1);
then
    $b.setScore($b.getScore() + 10);
    $b.setDetailImages($b.getDetailImages() + 10);
end

rule "detailImageLessThreeII"
when
    $b : BusinChance(lessThreeHundred == 2);
then
    $b.setScore($b.getScore() + 30);
    $b.setDetailImages($b.getDetailImages() + 30);
end

rule "detailImageLessThreeIII"
when
    $b : BusinChance(lessThreeHundred >= 2);
then
    $b.setScore($b.getScore() + 50);
    $b.setDetailImages($b.getDetailImages() + 50);
end